<?php

// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Attendance - Register for a selected module
 *
 * @package    local_attendance
 * @copyright  2019, Oxford Brookes University
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 *
 */

require_once('../../config.php');
require_once($CFG->libdir . '/pdflib.php');
require_once('./db_update.php');
require_once('./module_register_form.php');

require_login();

$home = new moodle_url('/');
if (!is_siteadmin()) {
	redirect($home);
}

$dir = $home . 'local/attendance/';
$url = $dir . 'module_register.php';
$back = $dir . 'menu.php';

$id = optional_param('id', 0, PARAM_INT);
if ($id > 1) {
	$back .= '?id=' . $id;
}

$context = context_system::instance();
$PAGE->set_pagelayout('standard');
$PAGE->set_url($url);
$PAGE->set_context($context);
$PAGE->set_heading($SITE->fullname);
$PAGE->set_title(get_string('module_register', 'local_attendance'));

$message = '';

$today = intdiv(time(), 86400) * 86400;
$modules = get_staff_modules($USER->id, $today);
$moduleArray = array();
foreach ($modules as $module) {
	$moduleArray[$module->id] = $module->fullname;
}

$today = intdiv(time(), 86400) * 86400;
$sessions = get_staff_sessions($USER->id, $today);
$sessionArray = array();
foreach($sessions as $session) {
	$sessionArray[$session->sessdate] = date("d M y, H:i", $session->sessdate);
}

$parameters = [
	'id' => $id,
	'modules' => $moduleArray,
	'sessions' => $sessionArray
];

$mform = new module_register_form(null, $parameters);

if ($mform->is_cancelled()) {
    redirect($back);
} else if ($mform_data = $mform->get_data()) {
	$module = get_module_names($mform_data->module_id);
	$registers = get_register($mform_data->module_id, $mform_data->sessdate); // Get all attendees for selected session
	if (empty($registers)) {
		$message = get_string('no_register', 'local_attendance');
	} else {
		$pdf = new pdf();
	
		$pdf->SetTitle('Attendance register');
		$pdf->SetAuthor('Moodle ' . $CFG->release);
		$pdf->SetCreator('Moodle');
		$pdf->SetKeywords('');
		$pdf->SetSubject('Register generated by Moodle');
		$pdf->SetMargins(15, 15);
		
		$pdf->setPrintHeader(false);
		$pdf->setHeaderMargin(0);
		$pdf->setHeaderFont(array(PDF_FONT_NAME_MAIN, 'b', 10));
		$pdf->setHeaderData('', 0);
		$pdf->setPrintFooter(false);
		$pdf->setFooterMargin(10);
		$pdf->setFooterFont(array(PDF_FONT_NAME_MAIN, '', 8));

		output($pdf, $module, $registers, $mform_data->sessdate); // Clear the chamber
		
		exit();
	}	 
}

echo $OUTPUT->header();

if ($message) {
    notice($message, $url);    
}
else {
    $mform->display();
}

echo $OUTPUT->footer();

exit();


function output($pdf, $module, $registers, $sessdate) {

	$pdf->AddPage();
		
	$pdf->SetTextColor(255,255,255);
	$pdf->SetFillColor(255,255,255);
	$pdf->SetFont('helvetica', 'R', 24);
	$pdf->Cell(0, 0, 'Brookes Attendance Register', 0, 1, 'C', 1);
		
	$pdf->SetFont('helvetica', 'R', 10);
	$pdf->Ln(6);
	$pdf->SetTextColor(0,0,0);
	$pdf->SetPrintHeader(false);
	$pdf->SetMargins(PDF_MARGIN_LEFT, 10, PDF_MARGIN_RIGHT, true);

	
	$c = '';
	$c .= '<p style="text-align: center"><img src="./images/logo-brookes.png" align="center" width="100"></p>';
	
	$c .= '<h2>Register: ' . $module['Fullname'] . '</h2>';
	
	$first_value = reset($registers);
	$c .= '<h3>' . date('d/m/y H:i', $first_value->sessdate) . '</h3>';
		
	$c .= '<table border="0" cellspacing="0" cellpadding="3"><thead>';
	
	$c .= '<tr><th>Name</th><th>Student number</th><th width="25%">Present (signature)</th>';
	
	$c .= '</tr></thead><tbody>';
	$counter = 0;
	foreach ($registers as $register) {
		$counter ++;
		if ($counter % 2 == 0) {
			$c .= '<tr>';
		} else {
			$c .= '<tr bgcolor="#eeeeee">';
		}
			$c .= '<td align="left">' . $register->firstname . ' ' . $register->lastname . '</td>';
			$c .= '<td align="left">' . $register->username . '</td>';
			$c .= '<td>&nbsp;</td>';
			$c .= '</tr>';
		}
		
	
	$c .= '</tbody></table>';
	$c .= '<p>Total number of students: ' . $counter . '</p>';
	
	$pdf->writeHTML($c);
	$pdf->Output('register_' . $module['IDnumber'] . '.pdf');
}