<?php

// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Brookes ID - Certificates
 *
 * @package    local_attendance
 * @copyright  2017, Oxford Brookes University
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 *
 */

require_once('../../config.php');
require_once($CFG->libdir . '/pdflib.php');
require_once('./db_update.php');
require_once('./register_form.php');


require_login();
$context = context_system::instance();
require_capability('local/attendance:admin', $context);

$home = new moodle_url('/');
$url = $home . 'local/attendance/index.php';

$PAGE->set_pagelayout('standard');
$PAGE->set_url($url);
$PAGE->set_context($context);
$PAGE->set_heading($SITE->fullname);
$PAGE->set_title(get_string('attendance', 'local_attendance'));

$message = '';

$mform = new register_form(null, array());

if ($mform->is_cancelled()) {
    redirect($home);
} else if ($mform_data = $mform->get_data()) {
	$registers = get_register($mform_data->courseid, $mform_data->day); // Get all attendees for selected session
	$coursedetails = get_course_details($mform_data->courseid);
	if (empty($registers)) {
		$message = get_string('no_register', 'local_attendance');
	} else {
		$pdf = new pdf();
	
		$pdf->SetTitle('Attendance register');
		$pdf->SetAuthor('Moodle ' . $CFG->release);
		$pdf->SetCreator('Moodle');
		$pdf->SetKeywords('');
		$pdf->SetSubject('Register generated by Moodle');
		$pdf->SetMargins(15, 15);
		
		$pdf->setPrintHeader(false);
		$pdf->setHeaderMargin(0);
		$pdf->setHeaderFont(array(PDF_FONT_NAME_MAIN, 'b', 10));
		$pdf->setHeaderData('', 0);
		$pdf->setPrintFooter(false);
		$pdf->setFooterMargin(10);
		$pdf->setFooterFont(array(PDF_FONT_NAME_MAIN, '', 8));

		$studentnumber = 0;
		$day = date('d-m-Y h:i', $mform_data->day);
		$courseid = $mform_data->courseid;
		
		output($pdf, $registers, $coursedetails, $courseid, $day); // Clear the chamber
		$pdf->Output('register_' . $mform_data->courseid . '_' . date('d-m-Y h:i', $mform_data->day) . '.pdf');
		
		exit();
	}	 
}

echo $OUTPUT->header();

if ($message) {
    notice($message, $url);    
}
else {
    $mform->display();
}

echo $OUTPUT->footer();

exit();


function output($pdf, $registers, $coursedetails, $courseid, $day) {

	$pdf->AddPage();
		
	$pdf->SetTextColor(255,255,255);
	$pdf->SetFillColor(255,255,255);
	$pdf->SetFont('helvetica', 'R', 24);
	$pdf->Cell(0, 0, 'BrookesID Certificate', 0, 1, 'C', 1);
		
	$pdf->SetFont('helvetica', 'R', 12);
	$pdf->Ln(6);
	$pdf->SetTextColor(0,0,0);
	
	$c = '';
	$c .= '<p style="text-align: center"><img src="/pix/logo-brookes.png" align="center" width="100">';
	
	$c .= '<h2>Register</h2>';
	foreach ($coursedetails as $coursedetail) {
		$c .= '<h3>'. $coursedetail->idnumber  . ' ' . $coursedetail->shortname  .'</h3>';
	}
	
	$c .= '<table border="0" cellspacing="5" cellpadding="5"><thead>';
	
	$c .= '<tr><th width="5%">&nbsp;</th><th>Start time</th><th>Name</th><th>Student number</th><th width="25%">Present (signature)</th><th>Notes</th>';
	
	$c .= '</tr></thead><tbody>';
	$counter = 0;
	foreach ($registers as $register) {
		$counter ++;
		if ($counter % 2 == 0) {
			$c .= '<tr>';
		} else {
		 $c .= '<tr bgcolor="#eeeeee">';
		}
		$c .= '<td width="5%">' . $counter . '</td>';
		$c .= '<td>' . date('d/m/y h:i', $register->sessdate) . '</td>';
		$c .= '<td>' . $register->firstname . ' ' . $register->lastname . '</td>';
		$c .= '<td>' . $register->student_number . '</td>';
		$c .= '<td width="25%">&nbsp;</td><td>&nbsp;</td>';
		$c .= '</tr>';
		}
	
	$c .= '</tbody></table>';
	
	//$c .= '<br pagebreak="true"/>';
	
	
	
	$pdf->writeHTML($c);
}