<?php

// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Attendance - Register for given module
 *
 * @package    local_attendance
 * @copyright  2019, Oxford Brookes University
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 *
 */

require_once('../../config.php');
require_once($CFG->libdir . '/pdflib.php');
require_once('./db_update.php');
require_once('./register_form.php');

require_login();

$course = $DB->get_record('course', array('id' => required_param('id', PARAM_INT)), '*', MUST_EXIST);
context_helper::preload_course($course->id);
$context = context_course::instance($course->id, MUST_EXIST);
require_capability('mod/attendance:takeattendances', $context);

$home = new moodle_url('/');
$dir = $home . 'local/attendance/';
$url = $dir . 'register.php?id=' . $course->id;
$back = $dir . 'menu.php';

$PAGE->set_pagelayout('standard');
$PAGE->set_url($url);
$PAGE->set_course($course);
$PAGE->set_context($context);
$PAGE->set_heading($SITE->fullname);
$PAGE->set_title(get_string('register_pdf', 'local_attendance'));

$message = '';

$today = (floor(time() / 86400)) * 86400; // The timestamp at the start of the day
$parameters = [
	'id' => $course->id,
	'sessions' => get_sessions($course->id, $today)
];

$mform = new register_form(null, $parameters);

if ($mform->is_cancelled()) {
    redirect($back);
} else if ($mform_data = $mform->get_data()) {
	$registers = get_register($course->id, $mform_data->sessdate); // Get all attendees for selected session
	if (empty($registers)) {
		$message = get_string('no_register', 'local_attendance');
	} else {
		$pdf = new pdf();
	
		$pdf->SetTitle('Attendance register');
		$pdf->SetAuthor('Moodle ' . $CFG->release);
		$pdf->SetCreator('Moodle');
		$pdf->SetKeywords('');
		$pdf->SetSubject('Register generated by Moodle');
		$pdf->SetMargins(15, 15);
		
		$pdf->setPrintHeader(false);
		$pdf->setHeaderMargin(0);
		$pdf->setHeaderFont(array(PDF_FONT_NAME_MAIN, 'b', 10));
		$pdf->setHeaderData('', 0);
		$pdf->setPrintFooter(false);
		$pdf->setFooterMargin(10);
		$pdf->setFooterFont(array(PDF_FONT_NAME_MAIN, '', 8));

		$module = get_module_names($course->id);
		
		output($pdf, $module, $registers, $mform_data->sessdate);
		
		exit();
	}	 
}

echo $OUTPUT->header();

if ($message) {
    notice($message, $url);    
}
else {
    $mform->display();
}

echo $OUTPUT->footer();

exit();


function output($pdf, $module, $registers, $sessdate) {
	
	$pdf->AddPage();
		
	$pdf->SetTextColor(255,255,255);
	$pdf->SetFillColor(255,255,255);
	$pdf->SetFont('helvetica', 'R', 24);
	$pdf->SetPrintHeader(false);
	$pdf->Cell(0, 0, 'Brookes Attendance Register', 0, 1, 'C', 1);
		
	$pdf->SetFont('helvetica', 'R', 10);
	$pdf->Ln(6);
	$pdf->SetTextColor(0,0,0);
	$pdf->SetMargins(PDF_MARGIN_LEFT, 10, PDF_MARGIN_RIGHT, true);
	
	$c = '';
	$c .= '<p style="text-align: center"><img src="./images/logo-brookes.png" align="center" width="100">';
	
	$c .= '<h2>Register</h2>';
	$c .= '<h3>' . $module['Fullname'] . '</h3>';
	
	$first_value = reset($registers);
	$c .= '<p>' . date('d/m/y H:i', $first_value->sessdate) . '</p>';
		
	$c .= '<table border="0" cellspacing="0" cellpadding="3"><thead>';
	
	$c .= '<tr><th>Name</th><th>Student number</th><th width="25%">Present (signature)</th>';
	
	$c .= '</tr></thead><tbody>';
	$counter = 0;
	foreach ($registers as $register) {
		$counter ++;
		if ($counter % 2 == 0) {
			$c .= '<tr>';
		} else {
			$c .= '<tr bgcolor="#eeeeee">';
		}
		$c .= '<td align="left">' . $register->firstname . ' ' . $register->lastname . '</td>';
		$c .= '<td align="left">' . $register->username . '</td>';
		$c .= '<td>&nbsp;</td>';
		$c .= '</tr>';
	}
	
	$c .= '</tbody></table>';
	$c .= '<p>Total number of students: ' . $counter . '</p>';
	
	$pdf->writeHTML($c);
	$pdf->Output('register_' . $module['IDnumber'] . '.pdf');
}